# PerformTask.action

# 음료제조 작업

# Goal
int32 order_id       
int32 menu_id
int32 quantity
---
#Result
int32 order_id
bool success
int32 pick_up_num # 음료 픽업대 번호
string message
---
#Feedback
int32 order_id
float32 progress_percentage