# PickBook.action                  

# Goal         
string book_id
int32 carrier_slot_id # 도비 운반함
geometry_msgs/Pose book_pose
---
# Result         
string book_id
bool success         
string message # "1번 도서 픽업에 성공했습니다."
---
# Feedback         
string current_action         