# MoveToTarget.action

#목적지 이동

# Goal
geometry_msgs/Pose target_pose # 목적지 위치
string location_name # 목적지 명
---
# Result
bool success 
geometry_msgs/Pose final_pose # 최종 도착 위치
---
# Feedback
geometry_msgs/Pose current_pose # 현재 위치
float32 distance_remaining # 남은 거리