# 도서픽업 작업

# Goal 
int32 task_id  
string book_id
geometry_msgs/Pose2D shelf_approach_location # 책장 앞 접근 위치
geometry_msgs/Pose book_pick_pose 

int32 storage_id 
# 보관함 정보 (좌표)                
geometry_msgs/Pose2D storage_approach_location # 보관함 앞 접근 위치
geometry_msgs/Pose storage_slot_pose # 어느 칸인지

---
# Result 
int32 task_id 
bool success 
string message # "도서 픽업에 성공했습니다." or "도서 픽업에 실패했습니다"
float64 total_distance_m # 총 이동 거리
float64 total_time_sec # 총 작업 시간
---
# Feedback 넣지말지 고민중 상태는 토픽으로 보냄
int32 progress_percent         # 0~100