# 길안내 작업

# Goal
geometry_msgs/Pose2D dest_location # 목적지 위치
bool user_initiated # 사용자 주도 작업 여부 (true: GUI/VRC 요청, false: RCS 자동 할당)
---
# Result
bool success
int32 error_code # 에러코드 규칙 정해야 함
float64 total_distance_m # 총 이동 거리
float64 total_time_sec # 총 작업 시간
string message
---
# Feedback
float64 distance_remaining_m # 남은 거리
bool person_detected