routes:
  default:
    loop: true
    loop_pause_sec: 5.0
    waypoints:
      - { x: 0.0, y: 0.0, theta: 0.0 }
      - { x: 1.5, y: 0.0, theta: 0.0 }
      - { x: 1.5, y: 1.5, theta: 1.57 }
      - { x: 0.0, y: 1.5, theta: 3.14 }
